// AUTO-GENERATED: 180-word bank distributed across 100 phases
// Each phase: 6 words per category + 5 auto-generated quiz questions

export const CATEGORIES = [
  { id: 'nature',     title: 'Nature',     arabic: 'الطبيعة',      emoji: '🌿', color: '#4CAF50' },
  { id: 'technology', title: 'Technology', arabic: 'التكنولوجيا',  emoji: '💻', color: '#2196F3' },
  { id: 'emotions',   title: 'Emotions',   arabic: 'المشاعر',      emoji: '❤️', color: '#E91E63' },
  { id: 'science',    title: 'Science',    arabic: 'العلوم',        emoji: '🔬', color: '#9C27B0' },
  { id: 'travel',     title: 'Travel',     arabic: 'السفر',         emoji: '✈️', color: '#FF9800' },
  { id: 'food',       title: 'Food',       arabic: 'الطعام',        emoji: '🍎', color: '#F44336' },
];

export const TOTAL_PHASES = 100;

export const WORD_BANK = {
  nature: [
    {"word": "Ecosystem", "arabic": "النظام البيئي", "definition": "A community of living things interacting with each other and their environment.", "arabicDefinition": "مجتمع من الكائنات الحية تتفاعل مع بعضها ومع بيئتها.", "example": "The coral reef is a rich ecosystem full of diverse life.", "arabicExample": "الشعاب المرجانية نظام بيئي غني مليء بأشكال الحياة المتنوعة.", "pronunciation": "ee·koh·sis·tem", "emoji": "🌍"},
    {"word": "Habitat", "arabic": "الموئل", "definition": "The natural home or environment of an animal, plant, or organism.", "arabicDefinition": "الموطن الطبيعي أو البيئة التي يعيش فيها حيوان أو نبات أو كائن حي.", "example": "The polar bear's habitat is the Arctic ice.", "arabicExample": "موئل الدب القطبي هو جليد القطب الشمالي.", "pronunciation": "hab·i·tat", "emoji": "🏔️"},
    {"word": "Pollination", "arabic": "التلقيح", "definition": "The process of transferring pollen to fertilize plants and produce seeds.", "arabicDefinition": "عملية نقل حبوب اللقاح لتخصيب النباتات وإنتاج البذور.", "example": "Bees play a vital role in the pollination of flowers.", "arabicExample": "تلعب النحلات دوراً حيوياً في تلقيح الأزهار.", "pronunciation": "pol·i·nay·shun", "emoji": "🌸"},
    {"word": "Drought", "arabic": "الجفاف", "definition": "A long period with very little or no rainfall.", "arabicDefinition": "فترة طويلة تنعدم فيها الأمطار أو تكون شحيحة جداً.", "example": "The drought destroyed many crops across the region.", "arabicExample": "دمر الجفاف كثيراً من المحاصيل في المنطقة.", "pronunciation": "drowt", "emoji": "☀️"},
    {"word": "Erosion", "arabic": "التعرية", "definition": "The gradual wearing away of rock or soil by water, wind, or ice.", "arabicDefinition": "التآكل التدريجي للصخور أو التربة بفعل الماء أو الرياح أو الجليد.", "example": "Heavy rain caused serious erosion on the hillside.", "arabicExample": "تسببت الأمطار الغزيرة في تعرية شديدة على جانب التل.", "pronunciation": "i·roh·zhun", "emoji": "⛰️"},
    {"word": "Biodiversity", "arabic": "التنوع البيولوجي", "definition": "The variety of all living things in a given area.", "arabicDefinition": "تنوع جميع الكائنات الحية في منطقة معينة.", "example": "Rainforests contain incredible biodiversity.", "arabicExample": "تحتوي الغابات المطيرة على تنوع بيولوجي مذهل.", "pronunciation": "by·oh·di·ver·si·tee", "emoji": "🦋"},
    {"word": "Migration", "arabic": "الهجرة", "definition": "The seasonal movement of animals from one region to another.", "arabicDefinition": "تنقل الحيوانات الموسمي من منطقة إلى أخرى بحثاً عن الغذاء والدفء.", "example": "Every winter, thousands of birds make the long migration south.", "arabicExample": "في كل شتاء، تقطع آلاف الطيور رحلة هجرة طويلة نحو الجنوب.", "pronunciation": "mai·gray·shun", "emoji": "🦅"},
    {"word": "Camouflage", "arabic": "التمويه", "definition": "The ability to blend in with surroundings to avoid being seen.", "arabicDefinition": "القدرة على الاندماج مع البيئة المحيطة لتجنب الاكتشاف.", "example": "The chameleon uses camouflage to hide from predators.", "arabicExample": "يستخدم الحرباء التمويه للاختباء من الحيوانات المفترسة.", "pronunciation": "kam·uh·flahj", "emoji": "🦎"},
    {"word": "Predator", "arabic": "المفترس", "definition": "An animal that hunts and eats other animals.", "arabicDefinition": "حيوان يصطاد حيوانات أخرى ويتغذى عليها.", "example": "The lion is a powerful predator at the top of the food chain.", "arabicExample": "الأسد مفترس قوي يقف في قمة السلسلة الغذائية.", "pronunciation": "pred·uh·ter", "emoji": "🦁"},
    {"word": "Symbiosis", "arabic": "التكافل", "definition": "A relationship between two different species that benefits both.", "arabicDefinition": "علاقة بين نوعين مختلفين من الكائنات يستفيد منها كلاهما.", "example": "Bees and flowers have a symbiosis — bees get food, flowers get pollinated.", "arabicExample": "النحل والأزهار في علاقة تكافل — النحل يحصل على الغذاء والأزهار تتلقح.", "pronunciation": "sim·bee·oh·sis", "emoji": "🐝"},
    {"word": "Canopy", "arabic": "مظلة الغابة", "definition": "The upper layer of branches and leaves forming the roof of a forest.", "arabicDefinition": "الطبقة العليا من أغصان الأشجار وأوراقها التي تشكل سقف الغابة.", "example": "Monkeys swing through the canopy of the rainforest.", "arabicExample": "تتأرجح القرود عبر مظلة الغابة الاستوائية.", "pronunciation": "kan·uh·pee", "emoji": "🌳"},
    {"word": "Fossil", "arabic": "الحفرية", "definition": "Preserved remains or traces of ancient animals or plants found in rock.", "arabicDefinition": "بقايا أو آثار محفوظة لكائنات حية قديمة توجد داخل الصخور.", "example": "Scientists found a dinosaur fossil that was 65 million years old.", "arabicExample": "اكتشف العلماء حفرية ديناصور يبلغ عمرها 65 مليون سنة.", "pronunciation": "fos·ul", "emoji": "🦕"},
    {"word": "Deforestation", "arabic": "إزالة الغابات", "definition": "The large-scale clearing of forests by humans.", "arabicDefinition": "قطع الغابات وإزالتها على نطاق واسع بفعل الإنسان.", "example": "Deforestation is one of the biggest threats to wildlife.", "arabicExample": "إزالة الغابات من أكبر التهديدات التي تواجه الحياة البرية.", "pronunciation": "dee·for·es·tay·shun", "emoji": "🌲"},
    {"word": "Hibernation", "arabic": "السبات الشتوي", "definition": "A deep sleep some animals enter during winter to save energy.", "arabicDefinition": "نوم عميق تدخل فيه بعض الحيوانات خلال الشتاء لتوفير الطاقة.", "example": "Bears hibernate through the coldest months of winter.", "arabicExample": "يدخل الدب في سبات شتوي خلال أبرد أشهر الشتاء.", "pronunciation": "hy·ber·nay·shun", "emoji": "🐻"},
    {"word": "Metamorphosis", "arabic": "التحوّل", "definition": "A process of transformation in an animal's form during development.", "arabicDefinition": "عملية تحول في شكل الحيوان خلال مراحل نموه.", "example": "A caterpillar undergoes metamorphosis to become a butterfly.", "arabicExample": "تمر اليرقة بعملية تحوّل لتصبح فراشة.", "pronunciation": "met·uh·mor·fuh·sis", "emoji": "🦋"},
    {"word": "Glacier", "arabic": "النهر الجليدي", "definition": "A large, slow-moving mass of ice formed over many years.", "arabicDefinition": "كتلة ضخمة من الجليد تتحرك ببطء وتتكون على مدى سنوات طويلة.", "example": "Glaciers are melting faster due to climate change.", "arabicExample": "تذوب الأنهار الجليدية بشكل أسرع بسبب تغير المناخ.", "pronunciation": "glay·sher", "emoji": "🧊"},
    {"word": "Tide", "arabic": "المد والجزر", "definition": "The regular rise and fall of sea levels caused by the moon's gravity.", "arabicDefinition": "الارتفاع والانخفاض المنتظم لمستوى البحر الناتج عن جاذبية القمر.", "example": "The tide comes in twice a day along this coast.", "arabicExample": "يتكرر المد مرتين يومياً على امتداد هذا الساحل.", "pronunciation": "tyd", "emoji": "🌊"},
    {"word": "Altitude", "arabic": "الارتفاع", "definition": "The height of a place above sea level.", "arabicDefinition": "ارتفاع مكان ما فوق مستوى سطح البحر.", "example": "It is hard to breathe at very high altitude.", "arabicExample": "يصعب التنفس عند الارتفاعات العالية جداً.", "pronunciation": "al·ti·tood", "emoji": "🏔️"},
    {"word": "Estuary", "arabic": "مصب النهر", "definition": "The area where a river meets the sea, mixing fresh and salt water.", "arabicDefinition": "المنطقة التي يلتقي فيها النهر بالبحر فتختلط المياه العذبة بالمالحة.", "example": "Many fish species breed in the calm waters of an estuary.", "arabicExample": "تتكاثر أنواع كثيرة من الأسماك في المياه الهادئة لمصب النهر.", "pronunciation": "es·choo·er·ee", "emoji": "🐟"},
    {"word": "Savanna", "arabic": "السافانا", "definition": "A flat tropical grassland with scattered trees.", "arabicDefinition": "سهل مداري شاسع تتناثر فيه أشجار متفرقة.", "example": "Elephants and zebras roam the African savanna.", "arabicExample": "تتجول الأفيال والحمر الوحشية في السافانا الأفريقية.", "pronunciation": "suh·van·uh", "emoji": "🦒"},
    {"word": "Monsoon", "arabic": "موسم الأمطار", "definition": "A seasonal pattern of very heavy rains in tropical regions.", "arabicDefinition": "نمط موسمي من الأمطار الغزيرة جداً في المناطق الاستوائية.", "example": "The monsoon brings much-needed water to dry farmland.", "arabicExample": "يُحضر موسم الأمطار مياهاً ضرورية للأراضي الزراعية الجافة.", "pronunciation": "mon·soon", "emoji": "🌧️"},
    {"word": "Dormant", "arabic": "خامل / كامن", "definition": "Temporarily inactive, like a volcano that is not currently erupting.", "arabicDefinition": "غير نشط مؤقتاً، كبركان لا يثور في الوقت الحالي.", "example": "The volcano has been dormant for over a century.", "arabicExample": "ظل البركان خاملاً لأكثر من قرن من الزمن.", "pronunciation": "dor·munt", "emoji": "🌋"},
    {"word": "Flora", "arabic": "النباتات", "definition": "All the plants found in a particular region or time period.", "arabicDefinition": "جميع النباتات الموجودة في منطقة أو حقبة زمنية معينة.", "example": "The island has a unique flora found nowhere else on Earth.", "arabicExample": "يضم الجزيرة نباتات فريدة لا توجد في أي مكان آخر على الأرض.", "pronunciation": "flor·uh", "emoji": "🌺"},
    {"word": "Watershed", "arabic": "حوض الصرف", "definition": "The land area that drains rainwater into a particular river or lake.", "arabicDefinition": "المنطقة الأرضية التي تصرف مياه الأمطار إلى نهر أو بحيرة معينة.", "example": "Protecting the watershed keeps the river clean.", "arabicExample": "حماية حوض الصرف تُبقي النهر نظيفاً.", "pronunciation": "waw·ter·shed", "emoji": "💧"},
    {"word": "Aquifer", "arabic": "الطبقة المائية", "definition": "An underground layer of rock or soil that holds water.", "arabicDefinition": "طبقة جوفية من الصخور أو التربة تحتجز المياه.", "example": "People drill wells to reach water stored in an aquifer.", "arabicExample": "يحفر الناس آباراً للوصول إلى المياه المخزنة في الطبقة المائية.", "pronunciation": "ak·wi·fer", "emoji": "💧"},
    {"word": "Permafrost", "arabic": "الجليد الدائم", "definition": "Ground that remains frozen all year round, found in polar regions.", "arabicDefinition": "تربة تبقى متجمدة طوال العام وتوجد في المناطق القطبية.", "example": "Climate change is causing permafrost to thaw faster than ever.", "arabicExample": "يتسبب تغير المناخ في ذوبان الجليد الدائم أسرع من أي وقت مضى.", "pronunciation": "per·muh·frost", "emoji": "🧊"},
    {"word": "Bioluminescence", "arabic": "التألق الحيوي", "definition": "Light produced naturally by living organisms such as fireflies or deep-sea fish.", "arabicDefinition": "ضوء تنتجه الكائنات الحية بشكل طبيعي، كاليراعات وأسماك أعماق البحار.", "example": "The bay glowed blue at night from bioluminescence in the water.", "arabicExample": "توهج الخليج باللون الأزرق ليلاً بسبب التألق الحيوي في الماء.", "pronunciation": "by·oh·loo·mi·nes·ens", "emoji": "✨"},
    {"word": "Geothermal", "arabic": "الحراري الأرضي", "definition": "Relating to heat energy generated inside the Earth.", "arabicDefinition": "يتعلق بطاقة الحرارة المتولدة داخل باطن الأرض.", "example": "Iceland uses geothermal energy to heat homes and generate electricity.", "arabicExample": "تستخدم آيسلندا الطاقة الحرارية الأرضية لتدفئة المنازل وتوليد الكهرباء.", "pronunciation": "jee·oh·ther·mul", "emoji": "♨️"},
    {"word": "Humus", "arabic": "الدبال", "definition": "The dark, rich organic material in soil formed from decayed plants and animals.", "arabicDefinition": "المادة العضوية الداكنة الغنية في التربة والمتكونة من تحلل النباتات والحيوانات.", "example": "Adding humus to the garden makes the soil more fertile.", "arabicExample": "إضافة الدبال إلى الحديقة يجعل التربة أكثر خصوبة.", "pronunciation": "hyoo·mus", "emoji": "🌱"},
    {"word": "Riparian", "arabic": "النهري", "definition": "Related to or situated on the bank of a river or stream.", "arabicDefinition": "يتعلق بضفاف الأنهار أو الجداول أو يقع عليها.", "example": "Riparian plants help prevent soil erosion along river banks.", "arabicExample": "تساعد النباتات النهرية في منع تآكل التربة على ضفاف الأنهار.", "pronunciation": "ri·pair·ee·un", "emoji": "🏞️"},
  ],
  technology: [
    {"word": "Algorithm", "arabic": "الخوارزمية", "definition": "A set of rules or steps for solving a problem or completing a task.", "arabicDefinition": "مجموعة من القواعد أو الخطوات لحل مشكلة أو إنجاز مهمة.", "example": "Search engines use algorithms to find the most relevant results.", "arabicExample": "تستخدم محركات البحث خوارزميات لإيجاد النتائج الأكثر صلة.", "pronunciation": "al·go·ri·thum", "emoji": "🔢"},
    {"word": "Encryption", "arabic": "التشفير", "definition": "The process of converting data into a secret code to protect it.", "arabicDefinition": "عملية تحويل البيانات إلى رمز سري لحمايتها.", "example": "Banks use encryption to protect your financial data.", "arabicExample": "تستخدم البنوك التشفير لحماية بياناتك المالية.", "pronunciation": "en·krip·shun", "emoji": "🔐"},
    {"word": "Artificial Intelligence", "arabic": "الذكاء الاصطناعي", "definition": "The simulation of human intelligence by computer systems.", "arabicDefinition": "محاكاة الذكاء البشري بواسطة أنظمة الكمبيوتر.", "example": "Artificial intelligence can now beat humans at chess.", "arabicExample": "يستطيع الذكاء الاصطناعي الآن التغلب على البشر في لعبة الشطرنج.", "pronunciation": "ar·ti·fish·ul in·tel·i·jens", "emoji": "🤖"},
    {"word": "Bandwidth", "arabic": "عرض النطاق الترددي", "definition": "The maximum rate at which data can be transferred over a network.", "arabicDefinition": "الحد الأقصى لسرعة نقل البيانات عبر الشبكة.", "example": "Video streaming requires a lot of bandwidth.", "arabicExample": "يستهلك بث الفيديو كميات كبيرة من عرض النطاق الترددي.", "pronunciation": "band·width", "emoji": "📶"},
    {"word": "Database", "arabic": "قاعدة البيانات", "definition": "An organized collection of structured information stored electronically.", "arabicDefinition": "مجموعة منظمة من المعلومات المنظمة المخزنة إلكترونياً.", "example": "The hospital keeps patient records in a secure database.", "arabicExample": "يحتفظ المستشفى بسجلات المرضى في قاعدة بيانات آمنة.", "pronunciation": "day·tuh·bays", "emoji": "💾"},
    {"word": "Interface", "arabic": "واجهة المستخدم", "definition": "The point where a user interacts with a device or software.", "arabicDefinition": "النقطة التي يتفاعل فيها المستخدم مع جهاز أو برنامج.", "example": "A good interface makes apps easy to use.", "arabicExample": "واجهة المستخدم الجيدة تجعل التطبيقات سهلة الاستخدام.", "pronunciation": "in·ter·fays", "emoji": "🖥️"},
    {"word": "Processor", "arabic": "المعالج", "definition": "The main chip inside a computer that performs all calculations.", "arabicDefinition": "الشريحة الرئيسية داخل الكمبيوتر التي تُنفذ جميع العمليات الحسابية.", "example": "A faster processor makes your computer run programs more quickly.", "arabicExample": "المعالج الأسرع يجعل كمبيوترك يُشغّل البرامج بشكل أسرع.", "pronunciation": "pros·es·er", "emoji": "💻"},
    {"word": "Simulation", "arabic": "المحاكاة", "definition": "A computer model that imitates a real-world situation or process.", "arabicDefinition": "نموذج حاسوبي يُحاكي موقفاً أو عملية من العالم الحقيقي.", "example": "Pilots train using flight simulations before flying real planes.", "arabicExample": "يتدرب الطيارون باستخدام محاكاة الطيران قبل قيادة الطائرات الحقيقية.", "pronunciation": "sim·yuh·lay·shun", "emoji": "✈️"},
    {"word": "Firewall", "arabic": "جدار الحماية", "definition": "A security system that blocks unauthorized access to a network.", "arabicDefinition": "نظام أمني يمنع الوصول غير المصرح به إلى الشبكة.", "example": "The company installed a firewall to protect its data from hackers.", "arabicExample": "قامت الشركة بتثبيت جدار حماية لحماية بياناتها من المخترقين.", "pronunciation": "fai·er·wawl", "emoji": "🔥"},
    {"word": "Binary", "arabic": "النظام الثنائي", "definition": "A number system using only two digits, 0 and 1, used by computers.", "arabicDefinition": "نظام عددي يستخدم رقمين فقط هما 0 و1، وتعتمد عليه الحواسيب.", "example": "All computer data is stored as binary code using 0s and 1s.", "arabicExample": "تُخزَّن جميع بيانات الكمبيوتر كرمز ثنائي باستخدام الأصفار والآحاد.", "pronunciation": "bai·nuh·ree", "emoji": "🔢"},
    {"word": "Pixel", "arabic": "البكسل", "definition": "The smallest unit of a digital image or screen display.", "arabicDefinition": "أصغر وحدة في الصورة الرقمية أو شاشة العرض.", "example": "A high-resolution photo contains millions of tiny pixels.", "arabicExample": "تحتوي الصورة عالية الدقة على ملايين من وحدات البكسل الصغيرة.", "pronunciation": "pik·sel", "emoji": "🖼️"},
    {"word": "Cache", "arabic": "الذاكرة المؤقتة", "definition": "A small, fast memory that stores frequently used data for quick access.", "arabicDefinition": "ذاكرة صغيرة وسريعة تخزن البيانات المستخدمة كثيراً للوصول إليها بسرعة.", "example": "Your browser uses a cache to load websites faster.", "arabicExample": "يستخدم متصفحك ذاكرة مؤقتة لتحميل المواقع بشكل أسرع.", "pronunciation": "kash", "emoji": "⚡"},
    {"word": "Neural Network", "arabic": "الشبكة العصبية", "definition": "A computing system modeled on the human brain, used in AI.", "arabicDefinition": "نظام حوسبة مُصمَّم على غرار الدماغ البشري ويُستخدم في الذكاء الاصطناعي.", "example": "Neural networks help computers recognize faces in photos.", "arabicExample": "تساعد الشبكات العصبية الحواسيب على التعرف على الوجوه في الصور.", "pronunciation": "nyoor·ul net·werk", "emoji": "🧠"},
    {"word": "Blockchain", "arabic": "سلسلة الكتل", "definition": "A digital ledger that records transactions across many computers securely.", "arabicDefinition": "سجل رقمي يُسجّل المعاملات عبر حواسيب متعددة بشكل آمن.", "example": "Bitcoin uses blockchain technology to track all transactions.", "arabicExample": "يستخدم بيتكوين تقنية سلسلة الكتل لتتبع جميع المعاملات.", "pronunciation": "blok·chayn", "emoji": "⛓️"},
    {"word": "Augmented Reality", "arabic": "الواقع المعزز", "definition": "Technology that overlays digital information onto the real world.", "arabicDefinition": "تقنية تُضيف معلومات رقمية على العالم الحقيقي المرئي.", "example": "Augmented reality apps let you see furniture in your room before buying.", "arabicExample": "تتيح تطبيقات الواقع المعزز رؤية الأثاث في غرفتك قبل شرائه.", "pronunciation": "awg·men·ted ree·al·i·tee", "emoji": "👓"},
    {"word": "Autonomous", "arabic": "ذاتي التشغيل", "definition": "Able to operate independently without human control.", "arabicDefinition": "قادر على العمل باستقلالية دون تدخل بشري.", "example": "Autonomous cars can drive themselves using sensors and AI.", "arabicExample": "تستطيع السيارات ذاتية القيادة توجيه نفسها باستخدام أجهزة الاستشعار والذكاء الاصطناعي.", "pronunciation": "aw·ton·uh·mus", "emoji": "🚗"},
    {"word": "Cybersecurity", "arabic": "الأمن السيبراني", "definition": "The practice of protecting computers and networks from digital attacks.", "arabicDefinition": "ممارسة حماية أجهزة الكمبيوتر والشبكات من الهجمات الرقمية.", "example": "Cybersecurity experts work to keep personal data safe online.", "arabicExample": "يعمل خبراء الأمن السيبراني على حماية البيانات الشخصية على الإنترنت.", "pronunciation": "sy·ber·si·kyoor·i·tee", "emoji": "🔐"},
    {"word": "Quantum", "arabic": "الكم", "definition": "Relating to the smallest possible unit of energy or matter in physics.", "arabicDefinition": "يتعلق بأصغر وحدة ممكنة من الطاقة أو المادة في الفيزياء.", "example": "Quantum computers can solve problems millions of times faster.", "arabicExample": "يمكن للحواسيب الكمية حل المسائل أسرع بملايين المرات.", "pronunciation": "kwon·tum", "emoji": "⚛️"},
    {"word": "Protocol", "arabic": "البروتوكول", "definition": "A set of rules that govern how data is sent over a network.", "arabicDefinition": "مجموعة من القواعد التي تنظم كيفية إرسال البيانات عبر الشبكة.", "example": "HTTP is the protocol used to load web pages.", "arabicExample": "HTTP هو البروتوكول المستخدم لتحميل صفحات الويب.", "pronunciation": "proh·tuh·kol", "emoji": "🌐"},
    {"word": "Latency", "arabic": "التأخر", "definition": "The delay between sending a request and receiving a response.", "arabicDefinition": "التأخر الزمني بين إرسال طلب واستلام الاستجابة.", "example": "High latency causes lag in online video games.", "arabicExample": "يُسبب التأخر العالي تعثراً في ألعاب الفيديو الإلكترونية.", "pronunciation": "lay·ten·see", "emoji": "⏱️"},
    {"word": "Server", "arabic": "الخادم", "definition": "A computer that provides data or services to other computers.", "arabicDefinition": "حاسوب يُقدم بيانات أو خدمات لحواسيب أخرى.", "example": "The website runs on a powerful server in a data center.", "arabicExample": "يعمل الموقع على خادم قوي في مركز بيانات.", "pronunciation": "ser·ver", "emoji": "🖥️"},
    {"word": "Open Source", "arabic": "مفتوح المصدر", "definition": "Software whose source code is freely available for anyone to use or modify.", "arabicDefinition": "برنامج يكون كوده المصدري متاحاً مجاناً لأي شخص يستخدمه أو يعدّله.", "example": "Linux is a popular open source operating system.", "arabicExample": "لينكس نظام تشغيل مفتوح المصدر يحظى بشعبية واسعة.", "pronunciation": "oh·pun sors", "emoji": "💻"},
    {"word": "Variable", "arabic": "المتغير", "definition": "A named storage location that holds a value in a computer program.", "arabicDefinition": "موقع تخزين مُسمّى يحمل قيمة في برنامج حاسوبي.", "example": "The variable 'score' stores the player's points in the game.", "arabicExample": "يخزن المتغير 'score' نقاط اللاعب في اللعبة.", "pronunciation": "vair·ee·uh·bul", "emoji": "🔤"},
    {"word": "Syntax", "arabic": "بنية الكود", "definition": "The rules that define the correct structure of a programming language.", "arabicDefinition": "القواعد التي تحدد البنية الصحيحة للغة برمجية.", "example": "A missing semicolon can cause a syntax error in the code.", "arabicExample": "يمكن أن تُسبب الفاصلة المنقوطة المفقودة خطأً في بنية الكود.", "pronunciation": "sin·taks", "emoji": "📝"},
    {"word": "Rendering", "arabic": "المعالجة البصرية", "definition": "The process of generating a final image from a 3D model on a computer.", "arabicDefinition": "عملية توليد صورة نهائية من نموذج ثلاثي الأبعاد على الحاسوب.", "example": "3D movies require massive computing power for rendering.", "arabicExample": "تتطلب أفلام الثلاثي الأبعاد قدرة حاسوبية هائلة للمعالجة البصرية.", "pronunciation": "ren·der·ing", "emoji": "🎨"},
    {"word": "Scalable", "arabic": "قابل للتوسع", "definition": "Able to grow or handle more demand without losing performance.", "arabicDefinition": "قادر على النمو وتحمل طلب أكبر دون فقدان الأداء.", "example": "Cloud services are scalable — you pay only for what you use.", "arabicExample": "الخدمات السحابية قابلة للتوسع — تدفع فقط مقابل ما تستخدمه.", "pronunciation": "skay·luh·bul", "emoji": "📈"},
    {"word": "Token", "arabic": "الرمز المميز", "definition": "A small unit of data used to represent identity or grant access.", "arabicDefinition": "وحدة صغيرة من البيانات تُستخدم لتمثيل الهوية أو منح الوصول.", "example": "Your login token expires after 24 hours for security.", "arabicExample": "تنتهي صلاحية رمزك المميز للتسجيل بعد 24 ساعة لأسباب أمنية.", "pronunciation": "toh·ken", "emoji": "🎫"},
    {"word": "Wireless", "arabic": "لاسلكي", "definition": "Communication or technology that works without physical cables.", "arabicDefinition": "اتصال أو تقنية تعمل دون كابلات مادية.", "example": "Wireless headphones connect to your phone via Bluetooth.", "arabicExample": "تتصل سماعات الرأس اللاسلكية بهاتفك عبر البلوتوث.", "pronunciation": "wair·les", "emoji": "📡"},
    {"word": "Upload", "arabic": "رفع الملف", "definition": "The process of sending data from a local device to the internet or a server.", "arabicDefinition": "عملية إرسال البيانات من جهاز محلي إلى الإنترنت أو خادم.", "example": "She uploaded her photos to the cloud for safe storage.", "arabicExample": "رفعت صورها إلى السحابة لتخزينها بأمان.", "pronunciation": "up·lohd", "emoji": "☁️"},
    {"word": "Middleware", "arabic": "البرمجيات الوسيطة", "definition": "Software that connects different applications or systems together.", "arabicDefinition": "برنامج يربط تطبيقات أو أنظمة مختلفة ببعضها.", "example": "Middleware allows the mobile app to communicate with the database.", "arabicExample": "تُتيح البرمجيات الوسيطة للتطبيق المحمول التواصل مع قاعدة البيانات.", "pronunciation": "mid·ul·wair", "emoji": "🔗"},
  ],
  emotions: [
    {"word": "Empathy", "arabic": "التعاطف", "definition": "The ability to understand and share the feelings of another person.", "arabicDefinition": "القدرة على فهم مشاعر الآخرين والإحساس بها.", "example": "Good doctors show empathy toward their patients.", "arabicExample": "يُظهر الأطباء الجيدون تعاطفاً تجاه مرضاهم.", "pronunciation": "em·puh·thee", "emoji": "💗"},
    {"word": "Anxiety", "arabic": "القلق", "definition": "A feeling of worry and nervousness, often about something uncertain.", "arabicDefinition": "شعور بالتوتر والخوف، غالباً تجاه شيء غير مؤكد.", "example": "She felt anxiety before stepping on stage to speak.", "arabicExample": "شعرت بالقلق قبل صعودها إلى المسرح للتحدث.", "pronunciation": "ang·zy·uh·tee", "emoji": "😰"},
    {"word": "Resilience", "arabic": "الصمود", "definition": "The ability to recover quickly from difficulties or tough situations.", "arabicDefinition": "القدرة على التعافي بسرعة من الصعوبات أو المواقف الصعبة.", "example": "After losing the match, his resilience helped him train even harder.", "arabicExample": "بعد خسارته في المباراة، ساعده صموده على التدريب بجهد أكبر.", "pronunciation": "ri·zil·yens", "emoji": "💪"},
    {"word": "Euphoria", "arabic": "النشوة", "definition": "A feeling of intense happiness and excitement.", "arabicDefinition": "شعور بالسعادة الشديدة والإثارة.", "example": "Winning the championship filled the team with euphoria.", "arabicExample": "ملأ الفوز بالبطولة الفريق بالنشوة.", "pronunciation": "yoo·for·ee·uh", "emoji": "🎉"},
    {"word": "Nostalgia", "arabic": "الحنين إلى الماضي", "definition": "A sentimental longing for the past or for something once enjoyed.", "arabicDefinition": "شعور عاطفي بالحنين إلى الماضي أو لشيء كان يُستمتع به.", "example": "Looking at old photos filled her with nostalgia.", "arabicExample": "غمرها الحنين إلى الماضي حين نظرت إلى الصور القديمة.", "pronunciation": "nos·tal·juh", "emoji": "📷"},
    {"word": "Melancholy", "arabic": "الكآبة", "definition": "A feeling of deep, pensive sadness without a clear cause.", "arabicDefinition": "شعور بحزن عميق وتأملي دون سبب واضح.", "example": "A rainy day often brings on feelings of melancholy.", "arabicExample": "كثيراً ما تُصاحب الأيام الممطرة مشاعر من الكآبة.", "pronunciation": "mel·un·kol·ee", "emoji": "🌧️"},
    {"word": "Gratitude", "arabic": "الامتنان", "definition": "The feeling of being thankful and appreciating what you have.", "arabicDefinition": "الشعور بالشكر والتقدير لما تملكه.", "example": "She felt gratitude toward her teacher for all the help.", "arabicExample": "شعرت بالامتنان تجاه معلمتها على كل المساعدة التي تلقتها.", "pronunciation": "grat·i·tood", "emoji": "🙏"},
    {"word": "Curiosity", "arabic": "الفضول", "definition": "A strong desire to know or learn about something.", "arabicDefinition": "رغبة قوية في معرفة شيء ما أو تعلّمه.", "example": "His curiosity about space led him to become an astronaut.", "arabicExample": "أدى فضوله نحو الفضاء إلى أن أصبح رائد فضاء.", "pronunciation": "kyoor·ee·os·i·tee", "emoji": "🔍"},
    {"word": "Frustration", "arabic": "الإحباط", "definition": "The feeling of being annoyed or upset when you cannot achieve something.", "arabicDefinition": "الشعور بالانزعاج والضيق عند عدم القدرة على تحقيق شيء ما.", "example": "He felt frustration after failing the game level three times.", "arabicExample": "شعر بالإحباط بعد فشله في مستوى اللعبة ثلاث مرات.", "pronunciation": "frus·tray·shun", "emoji": "😤"},
    {"word": "Confidence", "arabic": "الثقة بالنفس", "definition": "A strong belief in your own abilities and judgment.", "arabicDefinition": "إيمان قوي بقدراتك الذاتية وحكمك على نفسك.", "example": "With confidence, she gave her speech in front of the class.", "arabicExample": "بثقة بالنفس، ألقت خطابها أمام الفصل.", "pronunciation": "kon·fi·dens", "emoji": "💪"},
    {"word": "Envy", "arabic": "الحسد", "definition": "The feeling of wanting something that someone else has.", "arabicDefinition": "الشعور بالرغبة في امتلاك ما يملكه شخص آخر.", "example": "She felt envy when she saw her friend's new bicycle.", "arabicExample": "شعرت بالحسد عندما رأت دراجة صديقتها الجديدة.", "pronunciation": "en·vee", "emoji": "😒"},
    {"word": "Pride", "arabic": "الفخر", "definition": "A deep feeling of satisfaction from your own or others' achievements.", "arabicDefinition": "شعور عميق بالرضا عن إنجازاتك أو إنجازات من هم قريبون منك.", "example": "His parents felt great pride when he graduated.", "arabicExample": "شعر والداه بفخر عظيم عندما تخرج.", "pronunciation": "pryd", "emoji": "🏅"},
    {"word": "Compassion", "arabic": "الشفقة", "definition": "Concern for others' suffering combined with a desire to help them.", "arabicDefinition": "الاكتراث بمعاناة الآخرين مع الرغبة في مساعدتهم.", "example": "The nurse showed great compassion toward the injured child.", "arabicExample": "أظهرت الممرضة شفقة بالغة تجاه الطفل المصاب.", "pronunciation": "kum·pash·un", "emoji": "💗"},
    {"word": "Jealousy", "arabic": "الغيرة", "definition": "A feeling of unhappiness because someone else has something you want.", "arabicDefinition": "شعور بعدم الرضا لأن شخصاً آخر يملك ما تريده أنت.", "example": "Jealousy can damage friendships if not handled carefully.", "arabicExample": "يمكن للغيرة أن تُتلف الصداقات إن لم تُعالَج بحكمة.", "pronunciation": "jel·uh·see", "emoji": "😠"},
    {"word": "Serenity", "arabic": "السكينة", "definition": "The state of being calm, peaceful, and untroubled.", "arabicDefinition": "حالة من الهدوء والسلام الداخلي والطمأنينة.", "example": "Sitting by the ocean gave her a deep sense of serenity.", "arabicExample": "منحها الجلوس بجانب المحيط إحساساً عميقاً بالسكينة.", "pronunciation": "suh·ren·i·tee", "emoji": "😌"},
    {"word": "Guilt", "arabic": "الشعور بالذنب", "definition": "The feeling of responsibility or remorse for doing something wrong.", "arabicDefinition": "الشعور بالمسؤولية أو الندم جراء ارتكاب شيء خاطئ.", "example": "He felt guilt after lying to his friend.", "arabicExample": "شعر بالذنب بعد أن كذب على صديقه.", "pronunciation": "gilt", "emoji": "😔"},
    {"word": "Awe", "arabic": "الدهشة والإعجاب", "definition": "A feeling of overwhelming wonder and respect for something great.", "arabicDefinition": "شعور بالدهشة الغامرة والإعجاب بشيء عظيم.", "example": "Standing at the edge of the Grand Canyon filled him with awe.", "arabicExample": "وقوفه على حافة الغراند كانيون غمره بالدهشة والإعجاب.", "pronunciation": "aw", "emoji": "🤩"},
    {"word": "Contentment", "arabic": "الرضا والقناعة", "definition": "A state of peaceful happiness and satisfaction with what you have.", "arabicDefinition": "حالة من السعادة الهادئة والرضا بما تملكه.", "example": "Simple moments with family brought her true contentment.", "arabicExample": "منحتها اللحظات البسيطة مع العائلة رضاً حقيقياً.", "pronunciation": "kun·tent·ment", "emoji": "😊"},
    {"word": "Admiration", "arabic": "الإعجاب", "definition": "A feeling of respect and warm approval for someone or something.", "arabicDefinition": "شعور بالاحترام والتقدير الحار تجاه شخص أو شيء ما.", "example": "She felt admiration for the athlete's hard work and dedication.", "arabicExample": "شعرت بالإعجاب بجهد الرياضي وتفانيه.", "pronunciation": "ad·mi·ray·shun", "emoji": "🌟"},
    {"word": "Boredom", "arabic": "الملل", "definition": "The state of feeling uninterested because nothing is engaging.", "arabicDefinition": "حالة من عدم الاهتمام لعدم وجود ما يشدّ الانتباه.", "example": "He played games on his phone to escape boredom on the long flight.", "arabicExample": "لعب الألعاب على هاتفه للهروب من الملل خلال الرحلة الطويلة.", "pronunciation": "bor·dum", "emoji": "😑"},
    {"word": "Determination", "arabic": "العزم والإصرار", "definition": "A firm decision to do something and not give up.", "arabicDefinition": "قرار ثابت بفعل شيء ما والإصرار على إنجازه.", "example": "Her determination helped her finish the race despite the pain.", "arabicExample": "ساعدها عزمها وإصرارها على إنهاء السباق رغم الألم.", "pronunciation": "di·ter·mi·nay·shun", "emoji": "🔥"},
    {"word": "Embarrassment", "arabic": "الإحراج", "definition": "A feeling of self-consciousness or shame in a social situation.", "arabicDefinition": "شعور بالخجل والتوتر الاجتماعي في موقف معين.", "example": "He turned red with embarrassment when he forgot his speech.", "arabicExample": "احمر خجلاً حين نسي خطابه أمام الجميع.", "pronunciation": "em·bar·us·ment", "emoji": "😳"},
    {"word": "Forgiveness", "arabic": "المغفرة", "definition": "The act of stopping feeling angry at someone for what they did wrong.", "arabicDefinition": "فعل التوقف عن الغضب على شخص ما بسبب خطئه.", "example": "Forgiveness helped her move on and find peace.", "arabicExample": "ساعدتها المغفرة على المضي قدماً وإيجاد السلام الداخلي.", "pronunciation": "fer·giv·nes", "emoji": "🕊️"},
    {"word": "Hope", "arabic": "الأمل", "definition": "A feeling that good things will happen in the future.", "arabicDefinition": "شعور بأن أشياء جيدة ستحدث في المستقبل.", "example": "Even in hard times, hope keeps us moving forward.", "arabicExample": "حتى في الأوقات الصعبة، يُبقينا الأمل نمضي قدماً.", "pronunciation": "hohp", "emoji": "🌅"},
    {"word": "Grief", "arabic": "الحزن العميق", "definition": "Deep sorrow, especially caused by the loss of someone or something.", "arabicDefinition": "حزن عميق، خاصة بسبب فقدان شخص أو شيء ما.", "example": "The whole community shared grief after the accident.", "arabicExample": "شاركت المجتمع كله في الحزن العميق بعد الحادث.", "pronunciation": "greef", "emoji": "💔"},
    {"word": "Loneliness", "arabic": "الوحدة", "definition": "A feeling of sadness because you are alone or lack company.", "arabicDefinition": "شعور بالحزن بسبب كونك وحيداً أو افتقارك إلى الصحبة.", "example": "Moving to a new city can cause loneliness at first.", "arabicExample": "قد يُسبب الانتقال إلى مدينة جديدة الشعور بالوحدة في البداية.", "pronunciation": "lohn·lee·nes", "emoji": "🌫️"},
    {"word": "Sympathy", "arabic": "المشاركة الوجدانية", "definition": "Understanding and caring about another person's feelings or situation.", "arabicDefinition": "الفهم والاهتمام بمشاعر شخص آخر أو وضعه.", "example": "Her friends expressed sympathy when she lost her pet.", "arabicExample": "أبدى أصدقاؤها مشاركة وجدانية حين فقدت حيوانها الأليف.", "pronunciation": "sim·puh·thee", "emoji": "🤝"},
    {"word": "Indifference", "arabic": "اللامبالاة", "definition": "Lack of interest, concern, or sympathy toward something.", "arabicDefinition": "غياب الاهتمام أو القلق أو التعاطف تجاه شيء ما.", "example": "His indifference to the problem made things worse.", "arabicExample": "أدت لامبالاته بالمشكلة إلى تفاقم الأمور.", "pronunciation": "in·dif·er·ens", "emoji": "😐"},
    {"word": "Excitement", "arabic": "الإثارة", "definition": "A feeling of enthusiasm and eagerness about something happening.", "arabicDefinition": "شعور بالحماس والشوق تجاه شيء ما يحدث.", "example": "The children's excitement grew as the holiday approached.", "arabicExample": "ازداد حماس الأطفال مع اقتراب العطلة.", "pronunciation": "ek·syt·ment", "emoji": "🎊"},
    {"word": "Overwhelmed", "arabic": "مرهق ومثقل", "definition": "Feeling buried under too much pressure, work, or emotion.", "arabicDefinition": "الشعور بثقل شديد بسبب الضغط الزائد أو العمل أو المشاعر.", "example": "She felt overwhelmed by all her homework and activities.", "arabicExample": "شعرت بأنها مثقلة بكل واجباتها وأنشطتها.", "pronunciation": "oh·ver·welmd", "emoji": "😵"},
  ],
  science: [
    {"word": "Hypothesis", "arabic": "الفرضية", "definition": "A proposed explanation that can be tested through experiments.", "arabicDefinition": "تفسير مقترح يمكن اختباره من خلال التجارب.", "example": "The scientist formed a hypothesis before running any tests.", "arabicExample": "صاغ العالم فرضيته قبل إجراء أي اختبارات.", "pronunciation": "hy·poth·uh·sis", "emoji": "🔬"},
    {"word": "Photosynthesis", "arabic": "التمثيل الضوئي", "definition": "The process plants use to convert sunlight into food using carbon dioxide and water.", "arabicDefinition": "العملية التي تستخدمها النباتات لتحويل ضوء الشمس إلى غذاء باستخدام ثاني أكسيد الكربون والماء.", "example": "Photosynthesis is why plants need sunlight to survive.", "arabicExample": "التمثيل الضوئي هو سبب حاجة النباتات لضوء الشمس كي تعيش.", "pronunciation": "foh·toh·sin·thuh·sis", "emoji": "🌿"},
    {"word": "Gravity", "arabic": "الجاذبية", "definition": "The force that attracts objects toward each other, keeping us on Earth.", "arabicDefinition": "القوة التي تجذب الأجسام نحو بعضها وتُبقينا على الأرض.", "example": "Gravity is what makes a ball fall to the ground.", "arabicExample": "الجاذبية هي ما يجعل الكرة تسقط على الأرض.", "pronunciation": "grav·i·tee", "emoji": "🍎"},
    {"word": "Atmosphere", "arabic": "الغلاف الجوي", "definition": "The layer of gases surrounding a planet, held in place by gravity.", "arabicDefinition": "طبقة الغازات المحيطة بالكوكب والمحتجزة فيه بفعل الجاذبية.", "example": "Earth's atmosphere protects us from harmful solar radiation.", "arabicExample": "يحمينا الغلاف الجوي للأرض من الإشعاعات الشمسية الضارة.", "pronunciation": "at·mos·feer", "emoji": "🌍"},
    {"word": "Evolution", "arabic": "التطور", "definition": "The gradual change in species over generations through natural selection.", "arabicDefinition": "التغير التدريجي في الأنواع عبر الأجيال من خلال الانتقاء الطبيعي.", "example": "Charles Darwin studied evolution on the Galapagos Islands.", "arabicExample": "درس تشارلز داروين التطور في جزر غالاباغوس.", "pronunciation": "ev·uh·loo·shun", "emoji": "🦎"},
    {"word": "Molecule", "arabic": "الجزيء", "definition": "The smallest unit of a substance that has all its chemical properties.", "arabicDefinition": "أصغر وحدة من مادة ما تحتفظ بجميع خصائصها الكيميائية.", "example": "Water is made of molecules with two hydrogen and one oxygen atom.", "arabicExample": "الماء مكون من جزيئات تحتوي على ذرتي هيدروجين وذرة أكسجين.", "pronunciation": "mol·uh·kyool", "emoji": "⚗️"},
    {"word": "Density", "arabic": "الكثافة", "definition": "The amount of mass contained in a given volume of a substance.", "arabicDefinition": "كمية المادة الموجودة في حجم معين من مادة ما.", "example": "Iron has a higher density than wood, which is why iron sinks in water.", "arabicExample": "الحديد أعلى كثافة من الخشب، لهذا يغرق الحديد في الماء.", "pronunciation": "den·si·tee", "emoji": "⚖️"},
    {"word": "Magnet", "arabic": "المغناطيس", "definition": "An object that produces a magnetic field and attracts metals like iron.", "arabicDefinition": "جسم ينتج مجالاً مغناطيسياً يجذب المعادن كالحديد.", "example": "The magnet pulled all the iron filings toward it.", "arabicExample": "جذب المغناطيس جميع برادة الحديد نحوه.", "pronunciation": "mag·net", "emoji": "🧲"},
    {"word": "Refraction", "arabic": "انكسار الضوء", "definition": "The bending of light as it passes from one material into another.", "arabicDefinition": "انحناء الضوء عند انتقاله من مادة إلى أخرى.", "example": "Refraction makes a straw in a glass of water appear bent.", "arabicExample": "يجعل انكسار الضوء المصّاصة في كأس الماء تبدو منحنية.", "pronunciation": "re·frak·shun", "emoji": "🌈"},
    {"word": "Catalyst", "arabic": "المحفّز", "definition": "A substance that speeds up a chemical reaction without being used up.", "arabicDefinition": "مادة تُسرّع التفاعل الكيميائي دون أن تُستهلك في العملية.", "example": "Enzymes act as catalysts in our body to help digest food.", "arabicExample": "تعمل الإنزيمات كمحفزات في جسمنا لمساعدتنا على هضم الطعام.", "pronunciation": "kat·uh·list", "emoji": "⚗️"},
    {"word": "Orbit", "arabic": "المدار", "definition": "The curved path of one celestial body as it moves around another.", "arabicDefinition": "المسار المنحني الذي يتبعه جرم سماوي في دورانه حول آخر.", "example": "Earth takes 365 days to complete one orbit around the Sun.", "arabicExample": "تستغرق الأرض 365 يوماً لإتمام دورة كاملة في مدارها حول الشمس.", "pronunciation": "or·bit", "emoji": "🪐"},
    {"word": "Chromosome", "arabic": "الكروموسوم", "definition": "A thread-like structure inside cells that carries genetic information.", "arabicDefinition": "بنية خيطية الشكل داخل الخلايا تحمل المعلومات الجينية.", "example": "Humans have 46 chromosomes that determine our traits.", "arabicExample": "يمتلك البشر 46 كروموسوماً تحدد صفاتنا الوراثية.", "pronunciation": "kroh·muh·sohm", "emoji": "🧬"},
    {"word": "Photon", "arabic": "الفوتون", "definition": "A tiny particle that carries light and electromagnetic radiation.", "arabicDefinition": "جسيم دقيق يحمل الضوء والإشعاع الكهرومغناطيسي.", "example": "Photons travel from the Sun to Earth in about 8 minutes.", "arabicExample": "تنتقل الفوتونات من الشمس إلى الأرض في حوالي 8 دقائق.", "pronunciation": "foh·ton", "emoji": "💡"},
    {"word": "Mitosis", "arabic": "الانقسام الخلوي", "definition": "The process by which a cell divides to produce two identical cells.", "arabicDefinition": "العملية التي تنقسم بها الخلية لإنتاج خليتين متماثلتين.", "example": "Mitosis allows our bodies to grow and repair damaged tissue.", "arabicExample": "يُتيح الانقسام الخلوي لجسمنا النمو وإصلاح الأنسجة التالفة.", "pronunciation": "my·toh·sis", "emoji": "🔬"},
    {"word": "Radiation", "arabic": "الإشعاع", "definition": "Energy that travels as waves or particles through space or matter.", "arabicDefinition": "طاقة تنتقل على شكل موجات أو جسيمات خلال الفضاء أو المادة.", "example": "X-rays use radiation to create images inside the body.", "arabicExample": "تستخدم الأشعة السينية الإشعاع لإنشاء صور داخل الجسم.", "pronunciation": "ray·dee·ay·shun", "emoji": "☢️"},
    {"word": "Vacuum", "arabic": "الفراغ", "definition": "A space that contains no matter or air at all.", "arabicDefinition": "فضاء لا يحتوي على أي مادة أو هواء.", "example": "Sound cannot travel through a vacuum in space.", "arabicExample": "لا يمكن للصوت أن ينتقل خلال الفراغ في الفضاء.", "pronunciation": "vak·yoom", "emoji": "🌌"},
    {"word": "Friction", "arabic": "الاحتكاك", "definition": "The force that resists movement when two surfaces rub against each other.", "arabicDefinition": "القوة التي تقاوم الحركة عند تلامس سطحين واحتكاكهما.", "example": "Friction is what makes your bicycle brakes work.", "arabicExample": "الاحتكاك هو ما يجعل مكابح دراجتك تعمل.", "pronunciation": "frik·shun", "emoji": "🔥"},
    {"word": "Element", "arabic": "العنصر الكيميائي", "definition": "A pure substance made entirely of one type of atom.", "arabicDefinition": "مادة نقية تتكون بالكامل من نوع واحد من الذرات.", "example": "Gold, oxygen, and carbon are all elements.", "arabicExample": "الذهب والأكسجين والكربون كلها عناصر كيميائية.", "pronunciation": "el·uh·ment", "emoji": "⚗️"},
    {"word": "Acceleration", "arabic": "التسارع", "definition": "The rate at which an object's speed or direction changes over time.", "arabicDefinition": "معدل تغير سرعة الجسم أو اتجاهه مع مرور الوقت.", "example": "A car accelerates when you press the gas pedal.", "arabicExample": "تتسارع السيارة عندما تضغط على دواسة الوقود.", "pronunciation": "ak·sel·er·ay·shun", "emoji": "🚀"},
    {"word": "Bacteria", "arabic": "البكتيريا", "definition": "Microscopic single-celled organisms found almost everywhere on Earth.", "arabicDefinition": "كائنات مجهرية وحيدة الخلية توجد في كل مكان تقريباً على الأرض.", "example": "Some bacteria cause illness, but others help our digestion.", "arabicExample": "تُسبب بعض البكتيريا الأمراض، بينما تساعد البعض الآخر على الهضم.", "pronunciation": "bak·teer·ee·uh", "emoji": "🦠"},
    {"word": "Carbon", "arabic": "الكربون", "definition": "A chemical element found in all living things and many materials.", "arabicDefinition": "عنصر كيميائي موجود في جميع الكائنات الحية وكثير من المواد.", "example": "Diamonds are made of pure carbon.", "arabicExample": "الماس مصنوع من الكربون النقي.", "pronunciation": "kar·bun", "emoji": "💎"},
    {"word": "Electron", "arabic": "الإلكترون", "definition": "A tiny negatively charged particle that orbits the nucleus of an atom.", "arabicDefinition": "جسيم صغير سالب الشحنة يدور حول نواة الذرة.", "example": "Electric current is the flow of electrons through a wire.", "arabicExample": "التيار الكهربائي هو تدفق الإلكترونات عبر السلك.", "pronunciation": "i·lek·tron", "emoji": "⚡"},
    {"word": "Gene", "arabic": "الجين", "definition": "A unit of hereditary information in DNA that controls traits.", "arabicDefinition": "وحدة من المعلومات الوراثية في الحمض النووي تتحكم في الصفات.", "example": "Eye color is determined by genes inherited from your parents.", "arabicExample": "يُحدد الجين لون العينين الموروث من الوالدين.", "pronunciation": "jeen", "emoji": "🧬"},
    {"word": "Ion", "arabic": "الأيون", "definition": "An atom or molecule with an electric charge due to gaining or losing electrons.", "arabicDefinition": "ذرة أو جزيء يحمل شحنة كهربائية بسبب اكتسابه أو فقدانه لإلكترونات.", "example": "Salt dissolves in water and splits into positive and negative ions.", "arabicExample": "يذوب الملح في الماء وينقسم إلى أيونات موجبة وسالبة.", "pronunciation": "ai·on", "emoji": "⚗️"},
    {"word": "Neutron", "arabic": "النيوترون", "definition": "A neutral particle found in the nucleus of an atom.", "arabicDefinition": "جسيم محايد يوجد في نواة الذرة.", "example": "Neutrons hold the atomic nucleus together with protons.", "arabicExample": "يُمسك النيوترون نواة الذرة مع البروتونات.", "pronunciation": "nyoo·tron", "emoji": "⚛️"},
    {"word": "Oxidation", "arabic": "الأكسدة", "definition": "A chemical reaction in which a substance loses electrons or reacts with oxygen.", "arabicDefinition": "تفاعل كيميائي تفقد فيه مادة ما إلكترونات أو تتفاعل مع الأكسجين.", "example": "Iron rusts due to oxidation when exposed to water and air.", "arabicExample": "يصدأ الحديد بسبب الأكسدة عند تعرضه للماء والهواء.", "pronunciation": "ok·si·day·shun", "emoji": "🔩"},
    {"word": "Fossil Fuel", "arabic": "الوقود الأحفوري", "definition": "Fuel formed from the remains of ancient plants and animals, like coal or oil.", "arabicDefinition": "وقود يتكون من بقايا نباتات وحيوانات قديمة، كالفحم والنفط.", "example": "Burning fossil fuels releases carbon dioxide into the atmosphere.", "arabicExample": "يُطلق حرق الوقود الأحفوري ثاني أكسيد الكربون في الغلاف الجوي.", "pronunciation": "fos·ul fyoo·ul", "emoji": "⛽"},
    {"word": "Laboratory", "arabic": "المختبر", "definition": "A room or building with special equipment for scientific experiments.", "arabicDefinition": "غرفة أو مبنى مجهز بمعدات خاصة لإجراء التجارب العلمية.", "example": "The students spent the afternoon doing experiments in the laboratory.", "arabicExample": "أمضى الطلاب بعد الظهر في إجراء تجارب في المختبر.", "pronunciation": "lab·ruh·tor·ee", "emoji": "🔬"},
    {"word": "Amino Acid", "arabic": "الحمض الأميني", "definition": "Building blocks that combine to form proteins in the body.", "arabicDefinition": "لبنات البناء التي تتحد لتكوين البروتينات في الجسم.", "example": "Our bodies need 20 different amino acids to build proteins.", "arabicExample": "يحتاج جسمنا إلى 20 حمضاً أمينياً مختلفاً لبناء البروتينات.", "pronunciation": "uh·mee·noh as·id", "emoji": "🧪"},
    {"word": "Decay", "arabic": "التحلل", "definition": "The gradual breakdown of organic matter by bacteria or fungi.", "arabicDefinition": "التفكك التدريجي للمادة العضوية بفعل البكتيريا أو الفطريات.", "example": "Dead leaves decay on the forest floor and enrich the soil.", "arabicExample": "تتحلل الأوراق الميتة على أرضية الغابة وتُثري التربة.", "pronunciation": "di·kay", "emoji": "🍂"},
  ],
  travel: [
    {"word": "Itinerary", "arabic": "خط سير الرحلة", "definition": "A detailed plan or list of places to visit during a trip.", "arabicDefinition": "خطة مفصلة أو قائمة بالأماكن التي ستزورها خلال رحلتك.", "example": "She planned a week-long itinerary before visiting Europe.", "arabicExample": "وضعت خطة سفر لمدة أسبوع قبل زيارة أوروبا.", "pronunciation": "ai·tin·er·er·ee", "emoji": "📋"},
    {"word": "Passport", "arabic": "جواز السفر", "definition": "An official document that proves your identity when traveling abroad.", "arabicDefinition": "وثيقة رسمية تُثبت هويتك عند السفر إلى الخارج.", "example": "You need a valid passport to travel to another country.", "arabicExample": "تحتاج إلى جواز سفر ساري المفعول للسفر إلى بلد آخر.", "pronunciation": "pas·port", "emoji": "📘"},
    {"word": "Currency", "arabic": "العملة", "definition": "The money used in a particular country.", "arabicDefinition": "النقود المستخدمة في بلد معين.", "example": "The local currency in Japan is the Japanese yen.", "arabicExample": "العملة المحلية في اليابان هي الين الياباني.", "pronunciation": "kur·en·see", "emoji": "💱"},
    {"word": "Landmark", "arabic": "المعلم البارز", "definition": "A famous or easily recognized structure or place.", "arabicDefinition": "منشأة أو مكان مشهور وسهل التعرف عليه.", "example": "The Eiffel Tower is a famous landmark in Paris.", "arabicExample": "برج إيفل معلم بارز مشهور في باريس.", "pronunciation": "land·mark", "emoji": "🗼"},
    {"word": "Souvenir", "arabic": "التذكار", "definition": "A small item kept as a reminder of a place you visited.", "arabicDefinition": "شيء صغير يُحتفظ به كتذكار لمكان زرته.", "example": "She bought a souvenir magnet from every country she visited.", "arabicExample": "اشترت مغناطيس تذكارياً من كل بلد زارته.", "pronunciation": "soo·vuh·neer", "emoji": "🛍️"},
    {"word": "Expedition", "arabic": "البعثة الاستكشافية", "definition": "A long organized journey for a specific purpose, like exploration.", "arabicDefinition": "رحلة منظمة طويلة لغرض محدد كالاستكشاف.", "example": "The team launched an expedition to explore the Amazon jungle.", "arabicExample": "أطلق الفريق بعثة استكشافية لاستكشاف غابة الأمازون.", "pronunciation": "eks·puh·dish·un", "emoji": "🧭"},
    {"word": "Visa", "arabic": "التأشيرة", "definition": "An official permission stamped in your passport to enter a foreign country.", "arabicDefinition": "إذن رسمي مختوم في جواز سفرك يسمح لك بدخول بلد أجنبي.", "example": "She applied for a visa before her trip to Japan.", "arabicExample": "تقدمت بطلب للحصول على تأشيرة قبل رحلتها إلى اليابان.", "pronunciation": "vee·zuh", "emoji": "🛂"},
    {"word": "Customs", "arabic": "الجمارك", "definition": "The border checkpoint where officials inspect your belongings.", "arabicDefinition": "نقطة التفتيش الحدودية حيث يفحص المسؤولون أمتعتك.", "example": "At customs, they asked him to open his suitcase for inspection.", "arabicExample": "في الجمارك، طلبوا منه فتح حقيبته للتفتيش.", "pronunciation": "kus·tumz", "emoji": "🛃"},
    {"word": "Turbulence", "arabic": "الاضطراب الجوي", "definition": "Sudden bumpy or rough movement of air that shakes an airplane.", "arabicDefinition": "حركة مفاجئة ومتقطعة للهواء تُهز الطائرة.", "example": "The pilot warned passengers about turbulence during the flight.", "arabicExample": "حذّر الطيار الركاب من الاضطراب الجوي أثناء الرحلة.", "pronunciation": "ter·byuh·lens", "emoji": "🌪️"},
    {"word": "Layover", "arabic": "التوقف المؤقت", "definition": "A stop in a city between two connecting flights.", "arabicDefinition": "توقف في مدينة ما بين رحلتين جويتين متواصلتين.", "example": "We had a six-hour layover in Dubai before flying to London.", "arabicExample": "كان لدينا توقف لمدة ست ساعات في دبي قبل التحليق إلى لندن.", "pronunciation": "lay·oh·ver", "emoji": "⏳"},
    {"word": "Hostel", "arabic": "النزل الشبابي", "definition": "A cheap accommodation where travelers share rooms and facilities.", "arabicDefinition": "مكان إقامة رخيص يتشارك فيه المسافرون الغرف والمرافق.", "example": "Backpackers often stay in hostels to save money while traveling.", "arabicExample": "يقيم المسافرون بالحقيبة في النزل الشبابي لتوفير المال أثناء السفر.", "pronunciation": "hos·tel", "emoji": "🏨"},
    {"word": "Departure", "arabic": "المغادرة", "definition": "The act of leaving a place, especially to begin a journey.", "arabicDefinition": "فعل مغادرة مكان ما، خاصة للشروع في رحلة.", "example": "Please arrive at the gate one hour before departure.", "arabicExample": "يُرجى الوصول إلى البوابة قبل ساعة من موعد المغادرة.", "pronunciation": "di·par·cher", "emoji": "🛫"},
    {"word": "Jet Lag", "arabic": "إرهاق السفر الجوي", "definition": "Extreme tiredness caused by flying across different time zones.", "arabicDefinition": "إرهاق شديد ناجم عن السفر عبر مناطق زمنية مختلفة.", "example": "After flying from New York to Tokyo, she had severe jet lag.", "arabicExample": "بعد طيرانها من نيويورك إلى طوكيو، عانت من إرهاق سفر جوي شديد.", "pronunciation": "jet lag", "emoji": "😴"},
    {"word": "Time Zone", "arabic": "المنطقة الزمنية", "definition": "A region of the world that uses the same standard time.", "arabicDefinition": "منطقة من العالم تستخدم نفس التوقيت الرسمي.", "example": "When it is noon in London, it is already 8 pm in Dubai.", "arabicExample": "عندما يكون الظهر في لندن، يكون الساعة الثامنة مساءً في دبي.", "pronunciation": "tym zohn", "emoji": "🕐"},
    {"word": "Backpacking", "arabic": "السفر بحقيبة الظهر", "definition": "Traveling independently on a low budget with minimal luggage.", "arabicDefinition": "السفر باستقلالية وميزانية منخفضة وحقيبة ظهر صغيرة.", "example": "She spent the summer backpacking through Southeast Asia.", "arabicExample": "أمضت الصيف تسافر عبر جنوب شرق آسيا بحقيبة الظهر.", "pronunciation": "bak·pak·ing", "emoji": "🎒"},
    {"word": "Embassy", "arabic": "السفارة", "definition": "The official office of one country's ambassador in another country.", "arabicDefinition": "المكتب الرسمي لسفير بلد ما في بلد آخر.", "example": "If you lose your passport abroad, visit your country's embassy.", "arabicExample": "إذا فقدت جواز سفرك في الخارج، توجّه إلى سفارة بلدك.", "pronunciation": "em·buh·see", "emoji": "🏛️"},
    {"word": "Nomad", "arabic": "الرحّال", "definition": "A person who moves from place to place without a permanent home.", "arabicDefinition": "شخص يتنقل من مكان لآخر دون مسكن ثابت.", "example": "Digital nomads work remotely while traveling the world.", "arabicExample": "يعمل الرحّالة الرقميون عن بُعد أثناء سفرهم حول العالم.", "pronunciation": "noh·mad", "emoji": "🏕️"},
    {"word": "Heritage", "arabic": "التراث", "definition": "Traditions, buildings, and values passed down from earlier generations.", "arabicDefinition": "التقاليد والمباني والقيم المتوارثة من الأجيال السابقة.", "example": "The ancient temples are part of the country's rich cultural heritage.", "arabicExample": "المعابد القديمة جزء من التراث الثقافي الغني للبلاد.", "pronunciation": "her·i·tij", "emoji": "🗺️"},
    {"word": "Destination", "arabic": "الوجهة", "definition": "The place you are traveling to or intending to reach.", "arabicDefinition": "المكان الذي تسافر إليه أو تقصد الوصول إليه.", "example": "Paris is a top travel destination for tourists worldwide.", "arabicExample": "باريس وجهة سفر رئيسية للسياح حول العالم.", "pronunciation": "des·ti·nay·shun", "emoji": "📍"},
    {"word": "Excursion", "arabic": "النزهة القصيرة", "definition": "A short journey taken for pleasure, usually as part of a holiday.", "arabicDefinition": "رحلة قصيرة تُقام للمتعة، عادةً في إطار إجازة.", "example": "We went on an excursion to a nearby island during our cruise.", "arabicExample": "ذهبنا في نزهة قصيرة إلى جزيرة قريبة خلال رحلتنا البحرية.", "pronunciation": "eks·ker·zhun", "emoji": "🚢"},
    {"word": "Immigration", "arabic": "الهجرة", "definition": "The process of entering and settling in a foreign country.", "arabicDefinition": "عملية الدخول إلى بلد أجنبي والاستقرار فيه.", "example": "The immigration officer checked her visa at the airport.", "arabicExample": "فحص ضابط الهجرة تأشيرتها في المطار.", "pronunciation": "im·i·gray·shun", "emoji": "🌍"},
    {"word": "Guide", "arabic": "الدليل السياحي", "definition": "A person who leads and explains things to tourists in a place.", "arabicDefinition": "شخص يقود السياح ويشرح لهم المعالم في مكان ما.", "example": "Our guide told us fascinating stories about the ancient ruins.", "arabicExample": "أخبرنا دليلنا السياحي قصصاً رائعة عن الأطلال القديمة.", "pronunciation": "gyd", "emoji": "🗺️"},
    {"word": "Luggage", "arabic": "الأمتعة", "definition": "Bags, suitcases, and other items taken on a journey.", "arabicDefinition": "الحقائب والشنط والأغراض الأخرى التي تأخذها معك في رحلة.", "example": "She packed her luggage the night before the flight.", "arabicExample": "حزمت أمتعتها في الليلة التي سبقت الرحلة.", "pronunciation": "lug·ij", "emoji": "🧳"},
    {"word": "Map", "arabic": "الخريطة", "definition": "A diagram or picture showing geographic features of an area.", "arabicDefinition": "رسم أو صورة تُظهر المعالم الجغرافية لمنطقة ما.", "example": "He used a paper map when his phone's GPS stopped working.", "arabicExample": "استخدم خريطة ورقية حين توقف نظام GPS في هاتفه.", "pronunciation": "map", "emoji": "🗺️"},
    {"word": "Resort", "arabic": "المنتجع", "definition": "A place with hotels and facilities designed for vacationing.", "arabicDefinition": "مكان يضم فنادق ومرافق مصممة لقضاء العطل.", "example": "They spent a relaxing week at a beach resort.", "arabicExample": "أمضوا أسبوعاً مريحاً في منتجع شاطئي.", "pronunciation": "ri·zort", "emoji": "🏖️"},
    {"word": "Altitude Sickness", "arabic": "مرض الارتفاع", "definition": "Illness caused by traveling to high places where oxygen is thin.", "arabicDefinition": "مرض يُسببه الصعود إلى أماكن مرتفعة حيث يكون الأكسجين شحيحاً.", "example": "Many hikers get altitude sickness when climbing tall mountains.", "arabicExample": "يُصاب كثير من المتسلقين بمرض الارتفاع عند تسلق الجبال الشاهقة.", "pronunciation": "al·ti·tood sik·nes", "emoji": "🏔️"},
    {"word": "Foreign Exchange", "arabic": "صرف العملات", "definition": "Converting one currency into another when traveling abroad.", "arabicDefinition": "تحويل عملة إلى أخرى عند السفر إلى الخارج.", "example": "She used a foreign exchange booth at the airport to get local cash.", "arabicExample": "استخدمت نقطة صرف العملات في المطار للحصول على نقد محلي.", "pronunciation": "for·en eks·chaynj", "emoji": "💱"},
    {"word": "Brochure", "arabic": "الكتيب السياحي", "definition": "A small booklet with pictures and information about a place.", "arabicDefinition": "كتيب صغير يحتوي على صور ومعلومات حول مكان ما.", "example": "The tourist office gave us a colorful brochure about the city.", "arabicExample": "أعطانا مكتب السياحة كتيباً ملوناً عن المدينة.", "pronunciation": "broh·shur", "emoji": "📖"},
    {"word": "Transit", "arabic": "العبور", "definition": "Passing through a place on the way to your final destination.", "arabicDefinition": "المرور عبر مكان ما في طريقك إلى وجهتك النهائية.", "example": "Passengers in transit do not need to pass through customs.", "arabicExample": "لا يحتاج المسافرون في العبور إلى المرور بالجمارك.", "pronunciation": "tran·zit", "emoji": "🚉"},
    {"word": "Connecting Flight", "arabic": "الرحلة المتواصلة", "definition": "A flight that requires changing planes at an intermediate airport.", "arabicDefinition": "رحلة جوية تستلزم تغيير الطائرة في مطار وسيط.", "example": "Our connecting flight in Amsterdam was delayed by two hours.", "arabicExample": "تأخرت رحلتنا المتواصلة في أمستردام لساعتين.", "pronunciation": "kuh·nek·ting flyt", "emoji": "✈️"},
  ],
  food: [
    {"word": "Nutrition", "arabic": "التغذية", "definition": "The process of providing food necessary for health and growth.", "arabicDefinition": "عملية توفير الغذاء الضروري للصحة والنمو.", "example": "Good nutrition is essential for a healthy body and mind.", "arabicExample": "التغذية الجيدة ضرورية لجسم وعقل سليمين.", "pronunciation": "nyoo·trish·un", "emoji": "🥗"},
    {"word": "Cuisine", "arabic": "المطبخ", "definition": "A style of cooking associated with a particular country or culture.", "arabicDefinition": "أسلوب الطهي المرتبط ببلد أو ثقافة معينة.", "example": "Italian cuisine is famous for its pasta and pizza.", "arabicExample": "المطبخ الإيطالي مشهور بالمعكرونة والبيتزا.", "pronunciation": "kwi·zeen", "emoji": "🍝"},
    {"word": "Protein", "arabic": "البروتين", "definition": "A nutrient found in meat, eggs, and beans that builds and repairs the body.", "arabicDefinition": "مادة مغذية توجد في اللحوم والبيض والفاصوليا وتبني الجسم وتُصلحه.", "example": "Athletes eat plenty of protein to build strong muscles.", "arabicExample": "يتناول الرياضيون كميات كبيرة من البروتين لبناء عضلات قوية.", "pronunciation": "proh·teen", "emoji": "🥩"},
    {"word": "Fermentation", "arabic": "التخمير", "definition": "A chemical process where sugars are converted into acids or alcohol.", "arabicDefinition": "عملية كيميائية تُحوَّل فيها السكريات إلى أحماض أو كحول.", "example": "Bread rises because yeast fermentation produces gas.", "arabicExample": "يرتفع الخبز لأن تخمير الخميرة يُنتج غازاً.", "pronunciation": "fer·men·tay·shun", "emoji": "🍞"},
    {"word": "Organic", "arabic": "العضوي", "definition": "Food grown without chemical pesticides or artificial fertilizers.", "arabicDefinition": "طعام يُزرع دون استخدام مبيدات كيميائية أو أسمدة صناعية.", "example": "Organic vegetables are grown without harmful chemicals.", "arabicExample": "تُزرع الخضروات العضوية دون استخدام مواد كيميائية ضارة.", "pronunciation": "or·gan·ik", "emoji": "🌱"},
    {"word": "Ingredient", "arabic": "المكوّن", "definition": "Any single food item used in making a recipe or dish.", "arabicDefinition": "أي مادة غذائية مفردة تُستخدم في تحضير وصفة أو طبق.", "example": "The secret ingredient in her sauce is a pinch of cinnamon.", "arabicExample": "المكوّن السري في صلصتها هو قليل من القرفة.", "pronunciation": "in·gree·dee·ent", "emoji": "🧂"},
    {"word": "Marinate", "arabic": "ينقع", "definition": "To soak food in a seasoned liquid before cooking to add flavor.", "arabicDefinition": "نقع الطعام في سائل متبّل قبل الطهي لإضافة النكهة.", "example": "She marinated the chicken in lemon juice and herbs overnight.", "arabicExample": "نقعت الدجاج في عصير الليمون والأعشاب طوال الليل.", "pronunciation": "mar·i·nayt", "emoji": "🍗"},
    {"word": "Simmer", "arabic": "يطهو على نار هادئة", "definition": "To cook gently in liquid just below boiling point.", "arabicDefinition": "الطهي ببطء في سائل عند درجة حرارة أقل من نقطة الغليان.", "example": "Let the soup simmer for 30 minutes to bring out the flavors.", "arabicExample": "دع الشوربة تطهو على نار هادئة لمدة 30 دقيقة لإبراز النكهات.", "pronunciation": "sim·er", "emoji": "🍲"},
    {"word": "Garnish", "arabic": "يُزيّن", "definition": "A small decoration added to a plate of food to make it look attractive.", "arabicDefinition": "زينة صغيرة تُضاف إلى طبق الطعام لجعله يبدو أكثر جاذبية.", "example": "The chef added fresh herbs as a garnish on the soup.", "arabicExample": "أضاف الطاهي أعشاباً طازجة كزينة على الشوربة.", "pronunciation": "gar·nish", "emoji": "🌿"},
    {"word": "Gluten", "arabic": "الغلوتين", "definition": "A protein found in wheat and grains that makes dough stretchy.", "arabicDefinition": "بروتين يوجد في القمح والحبوب يجعل العجين مرناً.", "example": "People with celiac disease cannot eat gluten.", "arabicExample": "لا يستطيع الأشخاص المصابون بمرض الاضطرابات الهضمية تناول الغلوتين.", "pronunciation": "gloo·ten", "emoji": "🌾"},
    {"word": "Portion", "arabic": "الحصة", "definition": "The amount of food served to one person in a meal.", "arabicDefinition": "كمية الطعام التي تُقدَّم لشخص واحد في وجبة.", "example": "The restaurant is known for its generous portions.", "arabicExample": "يُشتهر المطعم بحصصه السخية.", "pronunciation": "por·shun", "emoji": "🍽️"},
    {"word": "Spice", "arabic": "البهار", "definition": "A substance from plants used to add flavor or aroma to food.", "arabicDefinition": "مادة مستخلصة من النباتات تُستخدم لإضافة نكهة أو عطر للطعام.", "example": "Cinnamon and cumin are popular spices in Arabic cooking.", "arabicExample": "القرفة والكمون من البهارات الشائعة في الطبخ العربي.", "pronunciation": "spais", "emoji": "🌶️"},
    {"word": "Pasteurize", "arabic": "يُبستر", "definition": "To heat food or drink to a specific temperature to kill harmful bacteria.", "arabicDefinition": "تسخين الطعام أو الشراب إلى درجة حرارة معينة لقتل البكتيريا الضارة.", "example": "Milk is pasteurized to make it safe to drink.", "arabicExample": "يُبستَر الحليب ليكون آمناً للشرب.", "pronunciation": "pas·chuh·ryz", "emoji": "🥛"},
    {"word": "Vegan", "arabic": "نباتي صارم", "definition": "A person who does not eat or use any animal products at all.", "arabicDefinition": "شخص لا يتناول أي منتجات حيوانية أو يستخدمها على الإطلاق.", "example": "A vegan diet includes only plant-based foods.", "arabicExample": "يشتمل النظام الغذائي النباتي الصارم على الأطعمة النباتية فقط.", "pronunciation": "vee·gun", "emoji": "🥗"},
    {"word": "Calorie", "arabic": "السعرة الحرارية", "definition": "A unit that measures the amount of energy food provides to the body.", "arabicDefinition": "وحدة قياس تقيس كمية الطاقة التي يُوفرها الطعام للجسم.", "example": "A glass of orange juice contains about 110 calories.", "arabicExample": "تحتوي كأس عصير البرتقال على حوالي 110 سعرات حرارية.", "pronunciation": "kal·uh·ree", "emoji": "🔥"},
    {"word": "Texture", "arabic": "القوام", "definition": "The way food feels in your mouth when you eat it.", "arabicDefinition": "الطريقة التي يشعر بها الطعام في فمك عند تناوله.", "example": "The creamy texture of avocado makes it perfect for smoothies.", "arabicExample": "القوام الكريمي للأفوكادو يجعلها مثالية للعصائر المخفوقة.", "pronunciation": "teks·cher", "emoji": "🥑"},
    {"word": "Braise", "arabic": "يطهو ببطء", "definition": "To cook food slowly in a small amount of liquid in a covered pot.", "arabicDefinition": "طهي الطعام ببطء في كمية صغيرة من السائل في إناء مغطى.", "example": "The chef braised the lamb for three hours until it was very tender.", "arabicExample": "طهّى الطاهي لحم الضأن ببطء لثلاث ساعات حتى أصبح طرياً جداً.", "pronunciation": "brayz", "emoji": "🍖"},
    {"word": "Infuse", "arabic": "يُنقع لاستخلاص النكهة", "definition": "To steep an ingredient in liquid to extract its flavor or properties.", "arabicDefinition": "نقع مكوّن في سائل لاستخلاص نكهته أو خصائصه.", "example": "She infused the tea with mint leaves for extra flavor.", "arabicExample": "نقعت الشاي بأوراق النعناع لإضافة نكهة مميزة.", "pronunciation": "in·fyooz", "emoji": "🍵"},
    {"word": "Appetizer", "arabic": "المقبلات", "definition": "A small dish served before the main course to stimulate appetite.", "arabicDefinition": "طبق صغير يُقدَّم قبل الطبق الرئيسي لتحفيز الشهية.", "example": "We ordered hummus as an appetizer before the main meal.", "arabicExample": "طلبنا الحمص كمقبلات قبل الوجبة الرئيسية.", "pronunciation": "ap·uh·ty·zer", "emoji": "🥙"},
    {"word": "Condiment", "arabic": "البهار السائل", "definition": "A sauce or seasoning added to food at the table for extra flavor.", "arabicDefinition": "صلصة أو توابل تُضاف إلى الطعام على المائدة لإضافة نكهة إضافية.", "example": "Ketchup and mustard are popular condiments for burgers.", "arabicExample": "الكاتشب والخردل بهارات سائلة شائعة مع البرغر.", "pronunciation": "kon·di·ment", "emoji": "🍯"},
    {"word": "Delicacy", "arabic": "الطعام الشهي النادر", "definition": "A food that is considered special or rare in a particular culture.", "arabicDefinition": "طعام يُعدّ مميزاً أو نادراً في ثقافة معينة.", "example": "Saffron is an expensive delicacy used in Middle Eastern cooking.", "arabicExample": "الزعفران طعام شهي نادر وغالي الثمن يُستخدم في الطبخ الشرق أوسطي.", "pronunciation": "del·i·kuh·see", "emoji": "🌺"},
    {"word": "Fiber", "arabic": "الألياف", "definition": "A plant substance found in food that aids in digestion.", "arabicDefinition": "مادة نباتية توجد في الطعام وتُساعد على الهضم.", "example": "Fruits and vegetables are rich in fiber, which is good for digestion.", "arabicExample": "الفواكه والخضروات غنية بالألياف المفيدة للهضم.", "pronunciation": "fy·ber", "emoji": "🥦"},
    {"word": "Grilling", "arabic": "الشواء", "definition": "Cooking food over direct heat from a flame or hot coals.", "arabicDefinition": "طهي الطعام فوق حرارة مباشرة من لهب أو فحم ساخن.", "example": "Grilling vegetables gives them a delicious smoky flavor.", "arabicExample": "يُضفي الشواء على الخضروات نكهة مدخّنة شهية.", "pronunciation": "gril·ing", "emoji": "🔥"},
    {"word": "Halal", "arabic": "الحلال", "definition": "Food that is permissible under Islamic law for Muslims to eat.", "arabicDefinition": "طعام مباح وفق أحكام الشريعة الإسلامية للمسلمين.", "example": "He always checks if the restaurant serves halal meat.", "arabicExample": "يتحقق دائماً من أن المطعم يُقدم لحوماً حلالاً.", "pronunciation": "huh·lal", "emoji": "✅"},
    {"word": "Lactose", "arabic": "اللاكتوز", "definition": "A natural sugar found in milk and dairy products.", "arabicDefinition": "سكر طبيعي يوجد في الحليب ومنتجات الألبان.", "example": "Some people are lactose intolerant and cannot digest dairy well.", "arabicExample": "يعاني بعض الناس من عدم تحمل اللاكتوز وصعوبة في هضم منتجات الألبان.", "pronunciation": "lak·tohs", "emoji": "🥛"},
    {"word": "Broil", "arabic": "يشوي على نار مباشرة", "definition": "To cook food using high heat directly from above, like in an oven grill.", "arabicDefinition": "طهي الطعام باستخدام حرارة عالية مباشرة من الأعلى، كما في شواية الفرن.", "example": "She broiled the fish for 10 minutes until it was golden.", "arabicExample": "شوت السمك على نار مباشرة لمدة 10 دقائق حتى أصبح ذهبي اللون.", "pronunciation": "broyl", "emoji": "🐟"},
    {"word": "Extract", "arabic": "المستخلص", "definition": "A concentrated substance removed from a plant, used for flavoring.", "arabicDefinition": "مادة مركّزة مستخلصة من نبات تُستخدم للتطعيم.", "example": "Vanilla extract is used to flavor cakes and cookies.", "arabicExample": "يُستخدم مستخلص الفانيليا لتطعيم الكعك والبسكويت.", "pronunciation": "eks·trakt", "emoji": "🌿"},
    {"word": "Julienne", "arabic": "التقطيع الدقيق", "definition": "A way of cutting vegetables into thin, matchstick-sized strips.", "arabicDefinition": "طريقة في تقطيع الخضروات إلى شرائح رفيعة بحجم عيدان الكبريت.", "example": "She julienned the carrots for the salad.", "arabicExample": "قطّعت الجزر بطريقة التقطيع الدقيق لتضعه في السلطة.", "pronunciation": "joo·lee·en", "emoji": "🥕"},
    {"word": "Kosher", "arabic": "الكوشر", "definition": "Food prepared according to Jewish dietary laws.", "arabicDefinition": "طعام مُحضَّر وفق القوانين الغذائية اليهودية.", "example": "Kosher restaurants follow strict rules about how food is prepared.", "arabicExample": "تتبع مطاعم الكوشر قواعد صارمة في طريقة تحضير الطعام.", "pronunciation": "koh·sher", "emoji": "✡️"},
    {"word": "Smoothie", "arabic": "العصير المخفوق", "definition": "A thick drink made by blending fruit, vegetables, and often yogurt or milk.", "arabicDefinition": "مشروب كثيف يُحضَّر بخلط الفواكه والخضروات وغالباً الزبادي أو الحليب.", "example": "She makes a mango smoothie every morning for breakfast.", "arabicExample": "تُحضّر عصيراً مخفوقاً بالمانغا كل صباح للإفطار.", "pronunciation": "smoo·thee", "emoji": "🥤"},
  ],
};

// Returns 6 words for the given phase (0-indexed) for each category
export function getPhaseVocabulary(phaseIndex) {
  const perPhase = 6;
  const result = {};
  for (const cat of CATEGORIES) {
    const bank = WORD_BANK[cat.id];
    const bankSize = bank.length;
    // Use different offsets per cycle to increase variety
    const cycleLen = Math.floor(bankSize / perPhase);    // e.g. 5 cycles
    const cycle   = Math.floor(phaseIndex / cycleLen);
    const slot    = phaseIndex % cycleLen;
    // Shift start by 1 each cycle so words re-appear in different order
    const start   = ((slot * perPhase) + (cycle * 2)) % bankSize;
    const indices = Array.from({ length: perPhase }, (_, i) => (start + i) % bankSize);
    result[cat.id] = indices.map(idx => bank[idx]);
  }
  return result;
}

// Auto-generates 5 quiz questions from the 6 phase words
// Question: Arabic definition  |  Options: English words (correct + 3 distractors)
export function getPhaseQuiz(phaseIndex, categoryId) {
  const phaseWords = getPhaseVocabulary(phaseIndex)[categoryId];
  const bank       = WORD_BANK[categoryId];
  // Pick 5 of the 6 phase words as question subjects (rotate which one is skipped)
  const skipIdx = phaseIndex % phaseWords.length;
  const qWords  = phaseWords.filter((_, i) => i !== skipIdx);

  return qWords.map((targetWord, qi) => {
    // 3 distractors: deterministically chosen from the full bank
    const distractors = [];
    let di = (phaseIndex * 7 + qi * 3 + 1) % bank.length;
    while (distractors.length < 3) {
      const candidate = bank[di % bank.length];
      if (candidate.word !== targetWord.word &&
          !distractors.find(d => d.word === candidate.word)) {
        distractors.push(candidate);
      }
      di++;
    }
    // Place correct answer at a deterministic position
    const correctPos = (phaseIndex + qi) % 4;
    const options = [
      ...distractors.slice(0, correctPos),
      targetWord,
      ...distractors.slice(correctPos),
    ];
    return {
      question: targetWord.arabicDefinition + ' — ما الكلمة الإنجليزية الصحيحة؟',
      options:  options.map(o => o.word),
      answer:   correctPos,
    };
  });
}

// Helpers for backward compat (phase 0)
export const VOCABULARY = getPhaseVocabulary(0);
export const QUIZZES = Object.fromEntries(
  CATEGORIES.map(cat => [cat.id, getPhaseQuiz(0, cat.id)])
);